In [1]:
from __future__ import print_function
import torch

#### Empty matrix

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[            0.0000,             0.0000,            -0.0000],
        [            0.0000,            -0.0000,             0.0000],
        [-331121426432.0000,             0.0000, -331119329280.0000],
        [            0.0000,            -0.0000,             0.0000],
        [           -0.0000,             0.0000,            -0.0000]])


#### Random matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6746, 0.6652, 0.7379],
        [0.4909, 0.4697, 0.7957],
        [0.0358, 0.0384, 0.6215],
        [0.6302, 0.0117, 0.3485],
        [0.0321, 0.5155, 0.3314]])


#### Matrix of all zeroes and dtype long

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### Tensor directly from data

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2739, -0.4172, -0.2704],
        [-0.7328, -1.3026, -1.4376],
        [-0.3859,  0.1706,  0.4193],
        [ 0.8602,  0.1061,  0.0415],
        [-0.1406, -0.0106, -0.5113]])


#### get size

In [9]:
print(x.size())

torch.Size([5, 3])


### Operations

#### Addition

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5061,  0.1250,  0.5014],
        [-0.2085, -0.9704, -0.9819],
        [ 0.4896,  1.0403,  1.1991],
        [ 1.4063,  0.4644,  0.6366],
        [ 0.2595,  0.3620, -0.2931]])


In [11]:
print(torch.add(x, y))

tensor([[ 0.5061,  0.1250,  0.5014],
        [-0.2085, -0.9704, -0.9819],
        [ 0.4896,  1.0403,  1.1991],
        [ 1.4063,  0.4644,  0.6366],
        [ 0.2595,  0.3620, -0.2931]])


#### giving output result

In [12]:
result = torch.empty(5, 3)
torch.add(x, y , out=result)
print(result)

tensor([[ 0.5061,  0.1250,  0.5014],
        [-0.2085, -0.9704, -0.9819],
        [ 0.4896,  1.0403,  1.1991],
        [ 1.4063,  0.4644,  0.6366],
        [ 0.2595,  0.3620, -0.2931]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.5061,  0.1250,  0.5014],
        [-0.2085, -0.9704, -0.9819],
        [ 0.4896,  1.0403,  1.1991],
        [ 1.4063,  0.4644,  0.6366],
        [ 0.2595,  0.3620, -0.2931]])


In [14]:
print(x)

tensor([[-0.2739, -0.4172, -0.2704],
        [-0.7328, -1.3026, -1.4376],
        [-0.3859,  0.1706,  0.4193],
        [ 0.8602,  0.1061,  0.0415],
        [-0.1406, -0.0106, -0.5113]])


In [15]:
print(x[:, 1])

tensor([-0.4172, -1.3026,  0.1706,  0.1061, -0.0106])


#### Resizing: use torch.view() to reshape the tensor

In [18]:
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(y)
print(z)

tensor([0.2419, 0.2483, 0.1400, 0.4592, 0.5908, 0.7449, 0.7917, 0.1162, 0.2555,
        0.3667, 0.8589, 0.9977, 0.6606, 0.4540, 0.4453, 0.4383])
tensor([[0.2419, 0.2483, 0.1400, 0.4592, 0.5908, 0.7449, 0.7917, 0.1162],
        [0.2555, 0.3667, 0.8589, 0.9977, 0.6606, 0.4540, 0.4453, 0.4383]])


#### Convert torch tensor to numpy array

In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


#### Converting numpy array to torch tensor

In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### moving tensors to any device

In [30]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", dtype=torch.double))