In [1]:
import torch

In [2]:
torch.FloatTensor([2])

tensor([2.])

In [3]:
a = torch.FloatTensor([2])
b = torch.FloatTensor([3])

In [4]:
a + b

tensor([5.])

In [5]:
matrix = torch.randn(3, 3)

In [6]:
matrix

tensor([[-0.9324,  0.0108, -1.0211],
        [-0.0472, -0.5369, -0.9639],
        [ 0.4724, -0.3327, -0.8657]])

In [7]:
matrix.t()

tensor([[-0.9324, -0.0472,  0.4724],
        [ 0.0108, -0.5369, -0.3327],
        [-1.0211, -0.9639, -0.8657]])

In [8]:
from torch.autograd import Variable

In [9]:
x = Variable(train_x)

NameError: name 'train_x' is not defined

#### optimzer = torch.optim.Adam(model.parameters(), lr=learning_rate)

model = torch.nn.Sequential(
    torch.nn.Linear(input_num_units, hidden_num_units),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_num_units, output_num_units)
)

loss_fn = torch.nn.CrossEntropyLoss()